version: "3"

services:

  app:
    build:
      dockerfile: .docker/app/Dockerfile
      context: .
      target: dev
    container_name: video-catalog-app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s /entrypoint.sh
    environment:
      - _DB_HOST=db
      - _DB_DATABASE=ce_video_catalog
      - _DB_USERNAME=root
      - _DB_PASSWORD=root
      - _TEST_DB_DATABASE=ce_video_catalog_test
    volumes:
      - ./www:/var/www
    networks:
      - video-catalog-network
    depends_on:
      - db
      - redis

  nginx:
    build: .docker/nginx
    container_name: video-catalog-nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./www:/var/www
    networks:
      - video-catalog-network
    depends_on:
      - app

  db:
    build: ./.docker/mysql
    container_name: video-catalog-db
    restart: always
    tty: true
    ports:
      - "33006:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - video-catalog-network

  redis:
    image: redis:alpine
    container_name: video-catalog-redis
    expose:
      - 6379
    networks:
      - video-catalog-network

networks:
  video-catalog-network:
    driver: bridge
